### ISSUE TITLE
Mismatch between EIB pdf and linked mapping in doc

### ISSUE THREAD

**Issue by ablot** [open-ephys/eib-64#1]
In the onix documentation and in the readme.md the pin mapping points to this google doc: https://docs.google.com/spreadsheets/d/11wRDYOqHN5lPb03yUdfXfK0zvaDYsVetplaNK-R90Gg

In the google document, DF40 pin 37 is TT4B but in this repository, DF40 pin 37 is  LRG_GP SHLD_A. This is true for both eib-64/eib-64/eib-64.sch and the pdf version. 

It might be a version issue. The pdf and sch files indicate REV 1.3 and the mapping google doc rev 1.2. If that's the case, where can I find the rev1.2 schematics?

**Comment by ablot** [comment]
There is an other issue on the google doc. The nanoZ pin for TT14C is replaced by some wrongly copy/pasted text ("The EIB pinout (ephys input mapping, stimulation connections, etc) is located on this google sheet")

**Comment by jonnew** [comment]
Thanks @ablot. I'm going to communicate with the production site to see which SHA they are fabricating. After that I will create a tag for the proper version and correct these issues on the spreadsheets.

**Comment by jonnew** [comment]
- Fixed the nanoZ TT14C copy/paste error
- Added tag for rev. 1.2 that went into production (https://github.com/open-ephys/eib-64/releases/tag/rev-1.2)
- I believe your EIB should be rev 1.2 (you can check the silk screen) and the spreadsheet mapping should now be correct.
