### ISSUE TITLE
64ch EIB schematics for channel mapping not in main

### ISSUE THREAD

**Issue by ChucklesOnGitHub** [open-ephys/eib-64#3]
User pointed out the following:
File [eib-64.brd](https://github.com/open-ephys/eib-64/blob/main/eib-64/eib-64.brd) does not match the [channel map](https://docs.google.com/spreadsheets/d/1WYDymxNqGRtFPxn69H9JzeMgePpXcFSPHiWJYBE0lu4/edit#gid=0).

- On one side the file shows pad 69 routing to a channel/pin and pad 70 going to the reference (when the channel map lists pin 69 as a reference and pin 70 as the ground)

![image](https://github.com/open-ephys/eib-64/assets/16124331/8900f693-7fc9-4f74-84c1-20607797185a)

- On the other side it likewise shows pad 36 going to an anode (which matches the channel map), but pad 37 going to ground (when the channel map routes it to a channel/pin). 

![image](https://github.com/open-ephys/eib-64/assets/16124331/c97791df-f9bc-411d-a060-a2347448712e)

On a physical EIB the routing is correct with regards to the channel map: REF is connected to pin 69 and GND to pin 70. - i've now realized what it is, I must have been looking at a r1.2

It would seem the file does not match the boards?

This made me realize the channel map has to be updated to read v1.3 and have picture of EIB v1.3 since the current production version is 1.3 and not 1.2 - I can handle this but not the above.

![image](https://github.com/open-ephys/eib-64/assets/16124331/d4137b4a-29fe-44cb-8ac9-14cecfbe75d2)

**Comment by ChucklesOnGitHub** [comment]
I just realized the channel map for r1.3 is a different one, and that would solve it. Can you confirm so I can update the channel map google sheets?
![image](https://github.com/open-ephys/eib-64/assets/16124331/eaf705da-e521-419e-9b65-ca1eebfd0a26)

**Comment by jonnew** [comment]
We should deprecate 1.3 because it was never put in production (not that is
compatible with headstage rev 1.4, which also was never produced)

**Comment by jonnew** [comment]
The most recent distributed version is a release though, so I think to some extent this is handled. 

![image](https://github.com/open-ephys/eib-64/assets/1429475/48704cb5-466a-438a-a2a4-db9602d54613)

**Comment by jonnew** [comment]
In any case, I think we need to role back HEAD commit on this repo to 1.2 since its all that will ever be made. Additionally, we need a more easy to follow pin mapping picture which has a front view image of the headstage with each of the DF40 pins labeled and each individual pin hole labelled.

**Comment by ChucklesOnGitHub** [comment]
hi @jonnew I have in my hand an EIB that says r1.3, which as far as I understand is the same as r1.2 with an extra cannula hole. The problem is it is not the same r1.3 design on this repo, so it would be a roll back to r1.2 and then back up to 1.3 with the hole?

This is what I told the user back in Oct:

In principle, nothing has changed in the channel mapping between EIB r1.2 and r1.3 of the physical products we produce. The difference between these versions was meant to be the addition of an extra hole for cannulas.

The correct mapping should be the one on the google sheet, and I will update the label on the sheet to read r1.2 and r1.3

The team is working on tidying up the repo to reflect this, since there was a mistake with the "1.3" version that is uploaded there as you pointed out.

Both EIB versions are compatible with our Hirose based 64ch headstages.

**Comment by ChucklesOnGitHub** [comment]
The correct production files are in the corresponding branch, the issue is solved by merging.

Just for reassurance, here is the correct mapping file of the EIB that is currently in production.
[eib-64_schematic.pdf](https://github.com/open-ephys/eib-64/files/14671609/eib-64_schematic.pdf)

and it matches both current production versions of onix hs-64 and low-profile-hs-64-spi
[hs-64-spi - schematic.pdf](https://github.com/open-ephys/eib-64/files/14671615/hs-64-spi.-.schematic.pdf)
[headstage-64_schematic.pdf](https://github.com/open-ephys/eib-64/files/14671616/headstage-64_schematic.pdf)

I have updated the channel map google sheet accordingly and plan on making it more clear with updated pictures

**Comment by ChucklesOnGitHub** [comment]
For users to know which is the current manufactured version in case they want to access schematics or cad files, the following need to be main:
Repo: eib-64 - Branch: hw-dev-rev1.3. Tag rev1.3
Repo: onix-headstage-64 - Branch: rev-1.3B Tag rev-1.3B

- Additionally, the schematic information table inside file "headstage-64_schematic.pdf" in repo onix-headstage-64 mistakenly reads "1.2B", and should read "1.3B" otherwise it is impossible to know the version with the file alone

Outstanding on unifying this topic across repos is:
- have a public repo with the current manufactured files for nanoz adapter 1.0 with the tag rev1.0
- tag the adapter-64 with tag rev1.0

**Comment by jonnew** [comment]
As of right now:

- main is now the production branch
- The revision 1.3 release points to the current tip of main
- The incompatible version was move to rev-1.4-dev branch

@ChucklesOnGitHub please close this issue if this takes care of the problem

**Comment by ChucklesOnGitHub** [comment]
The original issue that pertains to this repo is solved, thank you.

I have put other related issues in their respective repos:
- https://github.com/open-ephys/adapter-hirose-omnetics-64/issues/2
- https://github.com/open-ephys/onix-headstage-64/issues/4
- https://github.com/open-ephys/onix-headstage-64/issues/3

Outstanding since I don't have a repo in which to open an issue:
- have a public repo with the current manufactured files for nanoz adapter 1.0 with the tag rev1.0
